arch: ''
baseNamespace: default
database:
  bluadminPwd: ''
  codeset: UTF-8
  collation: IDENTITY
  create: true
  encrypt: 'YES'
  name: BLUDB
  pageSize: '32768'
  tableOrg: COLUMN
  territory: US
dedicated: true
development: false
fcm:
  hostnetwork:
    enabled: false
  ips: ''
global:
  dbType: db2oltp
  serviceAccount: db2u
haRecovery: partial
hadr:
  enabled: false
  initRole: STANDARD
  peerWindow: '120'
  primaryPort: '60006'
  remoteHost: 'NULL'
  remoteInstanceUser: db2inst1
  scope: Namespace
  standbyPort: '60007'
  syncMode: NEARSYNC
  targetList: 'NULL'
  timeOut: '120'
ibm-unified-console:
  configMapName: ''
  dataServer:
    ldap:
      rootPwdSecretName: ''
    metadb:
      pwdSecretName: ''
    sharedPVC:
      name: null
      subPath:
        config: uc_config
        downloads: downloads
        userHome: home
  disableHostCheck: 'true'
  image:
    arch: ''
    pullPolicy: IfNotPresent
    repository: unified-console
    tag: icp4d-db2u
  product: PLATFORM_ICP4D_WH
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 1
      memory: 2Gi
  runtime: ICP4Data
  serviceName: ''
  useConfigMap: 'true'
images:
  auth:
    image:
      repository: db2u.auxiliary.auth
      tag: 11.5.1.0-CN1
    replicas: 1
  db2u:
    image:
      repository: db2u
      tag: 11.5.1.0-CN1
    replicas: 1
  etcd:
    image:
      repository: etcd
      tag: 3.3.10
    storage:
      persisted: true
    volume:
      name: etcd-stor
      size: 1Gi
      storageClassName: oketi-gluster
      useDynamicProvisioning: false
  instdb:
    image:
      repository: db2u.instdb
      tag: 11.5.1.0-CN1
    replicas: 1
  pullPolicy: IfNotPresent
  tools:
    image:
      repository: db2u.tools
      tag: 11.5.1.0-CN1
    replicas: 1
  universalTag: latest
instance:
  db2CompatibilityVector: 'NULL'
  db2FencedUser: db2fenc1
  db2InstanceGroup: db2iadm1
  db2InstanceMemPercent: '80'
  db2InstancePwd: ''
  db2InstanceUser: db2inst1
  db2Support4K: false
  db2Workload: ''
ldap:
  enabled: false
  ldap_admin: ''
  ldap_admin_group: ''
  ldap_domain: ''
  ldap_server: ''
  ldap_user_group: ''
limit:
  cpu: 1000m
  memory: 8Gi
mln:
  distribution: 0:0
  total: 0
nodes: ''
runtime: ICP
servicename: ''
setKernelParams: true
storage:
  catalogStor:
    size: 250Gi
  dataStor:
    size: 40Gi
  existingClaimName: ''
  persisted: true
  sqllibSharedStor:
    size: 2Gi
  storageClassName: ''
  storageLocation:
    backupStorage:
      enabled: false
      hostPath:
        path: ''
        type: Directory
      pvc:
        claim:
          size: 20Gi
          storageClassName: ''
          useDynamicProvisioning: false
        existingClaim:
          name: ''
      volumeName: backupvol
      volumeType: ''
    dataStorage:
      enabled: false
      hostPath:
        path: ''
        type: Directory
      pvc:
        claim:
          size: 40Gi
          storageClassName: ''
          useDynamicProvisioning: false
        existingClaim:
          name: ''
      volumeName: datavol
      volumeType: ''
    growthStorage:
      enabled: false
      hostPath:
        path: ''
        type: Directory
      pvc:
        claim:
          size: 40Gi
          storageClassName: ''
          useDynamicProvisioning: false
        existingClaim:
          name: ''
      volumeName: growthvol
      volumeType: ''
    metaStorage:
      enabled: false
      hostPath:
        path: ''
        type: Directory
      pvc:
        claim:
          size: 40Gi
          storageClassName: ''
          useDynamicProvisioning: false
        existingClaim:
          name: ''
      volumeName: metavol
      volumeType: ''
    tieredStorage:
      cold:
        enabled: false
        hostPath:
          path: ''
          type: Directory
        pvc:
          claim:
            size: 40Gi
            storageClassName: ''
            useDynamicProvisioning: false
          existingClaim:
            name: ''
        volumeName: tieredvolcold
        volumeType: ''
      cool:
        enabled: false
        hostPath:
          path: ''
          type: Directory
        pvc:
          claim:
            size: 40Gi
            storageClassName: ''
            useDynamicProvisioning: false
          existingClaim:
            name: ''
        volumeName: tieredvolcool
        volumeType: ''
      enabled: false
      hot:
        enabled: false
        hostPath:
          path: ''
          type: Directory
        pvc:
          claim:
            size: 40Gi
            storageClassName: ''
            useDynamicProvisioning: false
          existingClaim:
            name: ''
        volumeName: tieredvolhot
        volumeType: ''
      tiers:
        - hot
        - warm
        - cool
        - cold
      warm:
        enabled: false
        hostPath:
          path: ''
          type: Directory
        pvc:
          claim:
            size: 40Gi
            storageClassName: ''
            useDynamicProvisioning: false
          existingClaim:
            name: ''
        volumeName: tieredvolwarm
        volumeType: ''
  useDynamicProvisioning: false
  userHomeStor:
    existingClaimName: ''
subType: ''
zenServiceInstanceId: ''
